### ISSUE TITLE
TypeError: disconnect() failed between 'textChanged' and all its connections

### ISSUE THREAD

**Issue by PiRK** [TinosNitso/AutoCove-Plugin#2]
Hi. This was submitted as an Electrum ABC issue by a user, unfortunately without much context: 
https://github.com/Bitcoin-ABC/ElectrumABC/issues/175

I'm not sure if it is a bug in your code or a subtle difference between Electron Cash or Electrum ABC (unlikely, because I didn't touch the plugin code very much after forking Electron Cash).

# Traceback
```
Traceback (most recent call last):
  File "C:\Users\17193\AppData\Roaming\ElectrumABC\external_plugins\AutoCove-Plugin.zip\AutoCove\qt.py", line 663, in AsmBoxHighlighted
    def AsmBoxHighlighted(self,Index): self.AsmBox.setCurrentIndex(Index), self.AsmBoxActivated()   #Highlighted → Activated.
  File "C:\Users\17193\AppData\Roaming\ElectrumABC\external_plugins\AutoCove-Plugin.zip\AutoCove\qt.py", line 671, in AsmBoxActivated
    self.ColorsBox.setChecked(False), self.AsmBoxHighlighted(0), self.AsmBox.setCurrentIndex(Index), self.ColorsBox.setChecked(ColorsBool)
  File "C:\Users\17193\AppData\Roaming\ElectrumABC\external_plugins\AutoCove-Plugin.zip\AutoCove\qt.py", line 663, in AsmBoxHighlighted
    def AsmBoxHighlighted(self,Index): self.AsmBox.setCurrentIndex(Index), self.AsmBoxActivated()   #Highlighted → Activated.
  File "C:\Users\17193\AppData\Roaming\ElectrumABC\external_plugins\AutoCove-Plugin.zip\AutoCove\qt.py", line 672, in AsmBoxActivated
    self.ScriptBox.textChanged.disconnect(), self.ScriptBox.selectionChanged.disconnect()
TypeError: disconnect() failed between 'textChanged' and all its connections

```

# System information

- Electrum ABC version: 5.0.4
- Python version: 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
- Operating system: Windows-10-10.0.19041-SP0
- Wallet type: standard
- Locale: en_US

**Comment by TinosNitso** [comment]
I didn't know ElectrumABC had external plugins! I just tried ElectrumSV, but no luck with that one. 

I've discovered a bug with the `hex, asm, <dec>` conversion, but only in ElectrumABC, not Electron-Cash. It converts 0100 to 0, etc. I'll see if I can think of a simple fix for the next version. Aside from that I'm surprised how well everything works (just not the TXID examples, & Native Introspection OpCodes). Even [VanityTXID](https://github.com/TinosNitso/VanityTXID-Plugin) worked, but I haven't done anything on XEC's chain! I'll probably update VanityTXID before AutoCove.

Unfortunately I can't find the disconnect() bug. I'll leave the Issue open.

**Comment by TinosNitso** [comment]
I only tested `ElectrumABC-5.0.4-portable.exe`
Now with `ElectrumABC-5.0.4-setup` I'm getting a Severe Trojan threat. It happened when I tried to open the Installed Plugins... window.

Trojan: Win32/Bearfoos.B!ml

Alert level: Severe
Status: Active
Date: 1/02/2022 3:31 pm
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.
